### ISSUE TITLE
Class 'Url' not found 

### ISSUE THREAD

**Issue by bloomonkey2020** [concrete5-community-store/community_store_file_uploads#1]
Hi Mesuva, I using the File Upload on order package, but receiving this error. Can you help at all?

<img width="1078" alt="Screenshot 2021-02-26 at 12 23 56" src="https://user-images.githubusercontent.com/61829717/109303784-31da7e00-7833-11eb-8576-70f5eda92792.png">

Edit: Edit: I forgot to add that the image is uploaded to the right folder in the file manager, but I don't receive an notification of the file being uploaded as the system doesnt seem to get past this error screen. The order within the admin area also doesnt show any information of a file being uploaded.

**Comment by Mesuva** [comment]
Try this change, just looks like an oversight: 

https://github.com/concrete5-community-store/community_store_file_uploads/commit/7dbe1755637df92100564b3dc7c30456a9cefb23

**Comment by bloomonkey2020** [comment]
perfect thanks mesuva, works a treat
